name: Test and Deploy to TestPyPI

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.1.1-devel-ubuntu22.04

    steps:
      - name: Install system and Python dependencies
        run: |
          apt-get update && apt-get install -y \
            python3-pip python3-dev git build-essential \
            && ln -s /usr/bin/python3 /usr/bin/python

          pip install --upgrade pip
          pip install ninja torch numpy scikit-learn tqdm pytest build twine

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install warpgbm with CUDA arch flags
        run: |
          # Covers: V100 (7.0), T4 (7.5), A100 (8.0), RTX 30xx (8.6), L4 (8.9), H100 (9.0)
          export TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0;8.6;8.9;9.0"
          pip install .

      - name: Run tests
        run: |
          pytest tests/

      - name: Build wheel and sdist
        run: python -m build

      - name: Upload to TestPyPI if version changed
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          VERSION=$(cat version.txt)
          echo "Version: $VERSION"

          if git tag | grep -q "^v$VERSION-test$"; then
            echo "Version $VERSION-test already tagged — skipping upload."
          else
            echo "Uploading to TestPyPI..."
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag v$VERSION-test
            git push origin v$VERSION-test
          fi
