name: Test and Deploy to TestPyPI

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install CUDA Toolkit (11.7)
      run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu2004-11-7-local_11.7.0-470.57.02-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-7-local_11.7.0-470.57.02-1_amd64.deb
          sudo cp /var/cuda-repo-ubuntu2004-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-11-7
  
    - name: Set CUDA environment variable
      run: echo "CUDA_HOME=/usr/local/cuda-11.7" >> $GITHUB_ENV
  

    - name: Install dependencies (build CUDA extension)
      run: |
          pip install .[dev]
          pip install pytest build twine
  

    - name: Run tests
      run: pytest tests/

    - name: Build wheel and source distribution
      run: python -m build

    - name: Upload to TestPyPI if version changed
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        VERSION=$(cat version.txt)
        echo "Current version: $VERSION"

        if git tag | grep -q "^v$VERSION-test$"; then
          echo "Version $VERSION-test already tagged — skipping upload."
        else
          echo "Uploading version $VERSION to TestPyPI..."
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v$VERSION-test
          git push origin v$VERSION-test
        fi
