name: Test and Deploy to TestPyPI

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install pytest build twine

    - name: Run tests
      run: pytest tests/

    - name: Build wheel and source distribution
      run: python -m build

    - name: Upload to TestPyPI if version changed
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        VERSION=$(cat version.txt)
        echo "Current version: $VERSION"

        if git tag | grep -q "^v$VERSION-test$"; then
          echo "Version $VERSION-test already tagged — skipping upload."
        else
          echo "Uploading version $VERSION to TestPyPI..."
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v$VERSION-test
          git push origin v$VERSION-test
        fi
