name: Deploy to TestPyPI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Build wheel and sdist
        run: python -m build

      - name: Upload to TestPyPI if version changed
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          VERSION=$(cat version.txt)
          echo "Version: $VERSION"

          if git tag | grep -q "^v$VERSION-test$"; then
            echo "Version $VERSION-test already tagged — skipping upload."
          else
            echo "Uploading to TestPyPI..."
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag v$VERSION-test
            git push origin v$VERSION-test
          fi
